#!/bin/bash
# 截图整理脚本

echo "📸 VisionQuant-Pro 截图整理工具"
echo "=================================="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 确保你已经截了4张图"
echo "2. 将桌面的截图文件拖到这里："
echo ""
echo "方法1：手动重命名（推荐）"
echo "  - 找到桌面上的截图"
echo "  - 重命名为："
echo "    • screenshot1-main.png       (主界面)"
echo "    • screenshot2-portfolio.png  (批量分析)"
echo "    • screenshot3-backtest.png   (回测曲线)"
echo "    • screenshot4-ai-chat.png    (AI对话)"
echo ""
echo "  - 拖到项目的 docs/images/ 目录"
echo ""
echo "方法2：使用命令行"
echo "  cd ~/Desktop"
echo "  mv '截屏*.png' ~/PycharmProjects/pythonProject/VisionQuant-Pro/docs/images/"
echo ""
echo "=================================="
echo "完成后，运行以下命令上传到GitHub："
echo "  cd ~/PycharmProjects/pythonProject/VisionQuant-Pro"
echo "  git add docs/images/"
echo "  git commit -m 'docs: 添加项目截图'"
echo "  git push"
echo "=================================="
